### ISSUE TITLE
Is this project still alive or has it been superseded?

### ISSUE THREAD

**Issue by Sawtaytoes** [jsonnull/redux-render#1]
I've seen a lot of chatter lately about render props on React Redux. Sounds like they're going to consider implementing something similar, but until then, I'm looking for a solution myself.

Is this project still alive and supported or has it been superseded by a more-popular library?

**Comment by jsonnull** [comment]
I still use and maintain this project.

Issues have been quiet since it currently fulfills its use-case. I have had some improvements in mind, namely supporting options like custom comparison functions—currently selecting the same Redux state doesn't propagate a re-render, when maybe you want to re-render for every dispatch.

If there's anything you feel missing or should be improved upon, I'm open to suggestions.

**Comment by Sawtaytoes** [comment]
Yeah, I do have some suggestions; although, I'd have to get approval as I rewrote it on company time.

I really appreciate you giving a good start though!
