### ISSUE TITLE
add render prop

### ISSUE THREAD

**Issue by kvnwolf** [jsonnull/redux-render#2]
Hello! I am using this library on an open source project I am working on [eoscostarica/dmeetup](https://github.com/eoscostarica/dmeetup)

The prop `render` has become a standard when using children as a function. So I think this package can be updated to support this convention.

```js
<Redux
  selector={state => state}
  render={(state) => <pre>{JSON.stringify(state, null, 2)}</pre>} />
```

**Comment by jsonnull** [comment]
Hello and sorry for the late reply!

I've seen most projects standardize on using `children` over `render`. One reason for this is that it affords you additional flexibility—you can use the children-as-function syntax or the prop syntax, however you prefer. For this reason, I don't see a huge benefit in making the change to use `render` instead of `children`.

**Comment by kvnwolf** [comment]
Well, we can also leave it to user's call. Just like `react-router` does.

**Comment by jsonnull** [comment]
Sure, that's worth considering.
